added code that will cause build to fail if it does not pass all tests

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -94,4 +94,6 @@ if $PASS; then
     echo "Build has succeeded!"
 else
     echo "Build has FAILED."
+    # 1 tells Jenkins that the build has failed
+    exit 1
 fi
